[deps]
DenseSpectralTransformation = "f7da9bbd-4e08-4b12-89eb-5f6f0acc2095"
JET = "c3a54625-cd67-489e-a8e7-0a5a0ff4e31b"

[compat]
DenseSpectralTransformation = "0.1.0"
julia = "1.11"

[sources]
DenseSpectralTransformation = { path = ".." }
