name = "DenseSpectralTransformation"
uuid = "f7da9bbd-4e08-4b12-89eb-5f6f0acc2095"
authors = ["Michael Stewart <mastewart@mastewart.org>"]
version = "0.1.0"

[deps]
BlockDiagonals = "0a1fb500-61f7-11e9-3c65-f5ef3456f9f0"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
BlockDiagonals = "0.1.42"
PrecompileTools = "1.2"
LinearAlgebra = "1.10"
Test = "1.10"
julia = "1.10"
