name = "DenseSpectralTransformation"
uuid = "f7da9bbd-4e08-4b12-89eb-5f6f0acc2095"
authors = ["Michael Stewart <mastewart@mastewart.org>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"

[compat]
LinearAlgebra = "1.10"
PrecompileTools = "1.2"
julia = "1.10"
